server:
  port: 4000

graphql:
  spqr:
    gui:
      enabled: true

# Data base
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:products
    username: sa
    password:
